### PR TITLE
Use src and tests directories

### PR DESCRIPTION
**Pull request by ryanhiebert**
Recent developments in Python packaging encourage using subdirectories to contain the python package and tests, at least partially because it gives better control over when the package shows up in the Python package. We may as well follow that advice.

### CODE REVIEW

**Comment by jayvdb** [comment]
I think the egg-info shouldnt be checked in. http://stackoverflow.com/questions/19375214/egg-info-directory-in-vc

**Comment by ryanhiebert** [comment]
You are completely correct. I'm going to do the unthinkable and rewrite the master branch. This was a mistake. Oops.

**Comment by ryanhiebert** [comment]
OK, that's done. The sin is committed, erasing my mistake.

**Comment by jayvdb** [comment]
;-)

**Pull request merged**
